package org.javalearning.variables;

public class VariableDefaultValueExample {
	
	int i;
	String s;
	double d;
	static float f;
	static char ch;
	static boolean b;
	
	// In instance variable and static variable default values are allocated by JVM but for local variable no default value generated by JVM.
	
	public void instanceMethod() {
		System.out.println("Default value of int in instance method : " + i);
		System.out.println("Default value of String in instance method : " + s);
		System.out.println("Default value of double in instance method : " + d);
		System.out.println("Default value of float in instance method : " + f);
		System.out.println("Default value of char in instance method : " + ch);
		System.out.println("Default value of boolean in instance method : " + b);
	}

	public static void main(String[] args) {
		VariableDefaultValueExample dv =  new VariableDefaultValueExample();
		System.out.println("Default value of int in static method : " + dv.i);
		System.out.println("Default value of String in static method : " + dv.s);
		System.out.println("Default value of double in static method : " + dv.d);
		System.out.println("Default value of float in static method : " + f);
		System.out.println("Default value of char in static method : " + ch);
		System.out.println("Default value of boolean in static method : " + b);
		dv.instanceMethod();

	}

}
