package org.javalearning.constructors;


/*Constructor:  
 1. It is used to write a block of java code that execute during object creation
 2. It is used to initialize instance variables during object creation
 3. If user didn't created any constructor then default constructor is generated by compiler during compilation
    But if user create at least single constructor then compiler doesn't create any constructor during compilation.
*/
public class ConstructorExample1 {

	
	void m1() {
		System.out.println("m1 method");
	}
	
	ConstructorExample1(){
		System.out.println("0-argument constructor");
	}
	
	ConstructorExample1(int a){
		System.out.println("1-argument constructor");
	}
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ConstructorExample1 c = new ConstructorExample1();
		c.m1();
		new ConstructorExample1(10);

	}

}
